/**
 * Over-Engineering Detector (V3)
 *
 * Detects overly complex code patterns commonly generated by AI models.
 * AI tends to produce unnecessarily complex solutions with:
 * - High cyclomatic complexity
 * - Excessively long functions
 * - Deep nesting
 * - Too many function parameters
 *
 * Uses pure text/regex analysis (no AST required).
 *
 * Implements the unified Detector interface.
 *
 * @since 0.3.0
 */

import type { Detector, UnifiedIssue, FileAnalysis, Severity } from '../types.js';
import { AIDefectCategory } from '../types.js';

// ─── Types ───

interface FunctionInfo {
  name: string;
  startLine: number;
  endLine: number;
  paramCount: number;
  lines: string[];
}

// ─── Function Extraction ───

/**
 * Extract function boundaries from source code using brace matching.
 * Handles: function declarations, arrow functions, methods.
 */
function extractFunctions(source: string): FunctionInfo[] {
  const functions: FunctionInfo[] = [];
  const lines = source.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Match function/method declarations
    const funcMatch = line.match(
      /(?:(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s+(\w+)|(?:(?:public|private|protected|static|async|override|get|set)\s+)*(\w+)\s*\([^)]*\)\s*(?::\s*[^{]+)?\s*\{|(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?\([^)]*\)\s*(?::\s*[^{=]+)?\s*=>)/,
    );

    if (!funcMatch) continue;

    const name = funcMatch[1] || funcMatch[2] || funcMatch[3] || 'anonymous';

    // Skip destructuring assignments or simple variable declarations
    if (/(?:const|let|var)\s*[\[{]/.test(line)) continue;
    if (/(?:const|let|var)\s+\w+\s*=\s*(?:['"`\d\[{]|new\s|null|undefined|true|false)/.test(line) && !line.includes('=>')) continue;

    // Count parameters
    const paramMatch = line.match(/\(([^)]*)\)/);
    let paramCount = 0;
    if (paramMatch && paramMatch[1].trim()) {
      paramCount = paramMatch[1].split(',').length;
    }

    // Find function body end using brace matching
    let braceDepth = 0;
    let started = false;
    let endLine = i;

    // For arrow functions without braces, it's a single expression
    if (line.includes('=>') && !line.includes('{')) {
      // Single-expression arrow function
      endLine = i;
      // Check if it spans multiple lines (parenthesized expression)
      let parenDepth = 0;
      for (let j = i; j < lines.length; j++) {
        for (const ch of lines[j]) {
          if (ch === '(') parenDepth++;
          if (ch === ')') parenDepth--;
        }
        endLine = j;
        if (parenDepth <= 0 && j > i) break;
        if (j === i && !lines[j].includes('(')) break;
      }
    } else {
      // Brace-delimited function body
      for (let j = i; j < lines.length; j++) {
        for (const ch of lines[j]) {
          if (ch === '{') { braceDepth++; started = true; }
          if (ch === '}') braceDepth--;
        }
        if (started && braceDepth === 0) {
          endLine = j;
          break;
        }
      }
    }

    if (endLine > i) {
      functions.push({
        name,
        startLine: i + 1,
        endLine: endLine + 1,
        paramCount,
        lines: lines.slice(i, endLine + 1),
      });
    }
  }

  return functions;
}

// ─── Complexity Metrics ───

/**
 * Compute cyclomatic complexity for a function body.
 * CC = 1 + count of decision points.
 */
function computeCyclomaticComplexity(bodyLines: string[]): number {
  let cc = 1;
  const body = bodyLines.join('\n');

  // Count branching keywords
  const patterns: RegExp[] = [
    /\bif\s*\(/g,
    /\belse\s+if\s*\(/g,
    /\bfor\s*\(/g,
    /\bfor\s+(?:const|let|var)\s+\w+\s+(?:of|in)\b/g,
    /\bwhile\s*\(/g,
    /\bdo\s*\{/g,
    /\bcase\s+[^:]+:/g,
    /\bcatch\s*\(/g,
    /\?\s*(?![:.])/g,     // ternary operator (but not ?. or ?:)
    /&&/g,
    /\|\|/g,
    /\?\?/g,
  ];

  for (const pattern of patterns) {
    const matches = body.match(pattern);
    if (matches) {
      cc += matches.length;
    }
  }

  // Subtract double-counted 'else if' (already counted by 'if')
  const elseIfMatches = body.match(/\belse\s+if\s*\(/g);
  if (elseIfMatches) {
    cc -= elseIfMatches.length;
  }

  return cc;
}

/**
 * Compute maximum nesting depth for a function body.
 */
function computeMaxNesting(bodyLines: string[]): number {
  let maxDepth = 0;
  let currentDepth = 0;
  // Start at -1 to account for the function's own opening brace
  let functionBrace = true;

  for (const line of bodyLines) {
    const trimmed = line.trim();
    // Skip comments
    if (trimmed.startsWith('//') || trimmed.startsWith('*') || trimmed.startsWith('/*')) continue;

    for (const ch of line) {
      if (ch === '{') {
        if (functionBrace) {
          functionBrace = false;
          continue;
        }
        currentDepth++;
        maxDepth = Math.max(maxDepth, currentDepth);
      }
      if (ch === '}') {
        currentDepth = Math.max(0, currentDepth - 1);
      }
    }
  }

  return maxDepth;
}

// ─── Thresholds ───

const THRESHOLDS = {
  complexity: { medium: 15, high: 25 },
  functionLength: { low: 80, medium: 150 },
  nestingDepth: { medium: 4, high: 6 },
  paramCount: { low: 5, medium: 8 },
} as const;

// ─── Main Detector ───

/**
 * OverEngineeringDetector — detects overly complex AI-generated code.
 *
 * Analyzes:
 * - Cyclomatic complexity per function
 * - Function length (line count)
 * - Maximum nesting depth
 * - Parameter count
 */
export class OverEngineeringDetector implements Detector {
  readonly name = 'over-engineering';
  readonly version = '1.0.0';
  readonly tier = 1 as const;

  // ─── V3 Unified Interface ───

  async detect(files: FileAnalysis[]): Promise<UnifiedIssue[]> {
    const allIssues: UnifiedIssue[] = [];
    let globalIndex = 0;

    for (const file of files) {
      const issues = this.analyzeFile(file.path, file.content);
      for (const issue of issues) {
        issue.id = `over-engineering:${globalIndex++}`;
        allIssues.push(issue);
      }
    }

    return allIssues;
  }

  // ─── Internal Analysis ───

  private analyzeFile(filePath: string, source: string): UnifiedIssue[] {
    const issues: UnifiedIssue[] = [];
    const functions = extractFunctions(source);

    for (const fn of functions) {
      const functionLength = fn.endLine - fn.startLine + 1;

      // 1. Cyclomatic Complexity
      const cc = computeCyclomaticComplexity(fn.lines);
      if (cc > THRESHOLDS.complexity.high) {
        issues.push(this.makeIssue(
          filePath, fn, 'high-complexity', 'high',
          `Function '${fn.name}' has cyclomatic complexity of ${cc} (threshold: ${THRESHOLDS.complexity.high})`,
          `Refactor into smaller functions. AI often generates monolithic functions with too many branches.`,
        ));
      } else if (cc > THRESHOLDS.complexity.medium) {
        issues.push(this.makeIssue(
          filePath, fn, 'high-complexity', 'medium',
          `Function '${fn.name}' has cyclomatic complexity of ${cc} (threshold: ${THRESHOLDS.complexity.medium})`,
          `Consider breaking this function into smaller, more focused functions.`,
        ));
      }

      // 2. Function Length
      if (functionLength > THRESHOLDS.functionLength.medium) {
        issues.push(this.makeIssue(
          filePath, fn, 'long-function', 'medium',
          `Function '${fn.name}' is ${functionLength} lines long (threshold: ${THRESHOLDS.functionLength.medium})`,
          `Break into smaller functions. AI tends to generate long, monolithic functions.`,
        ));
      } else if (functionLength > THRESHOLDS.functionLength.low) {
        issues.push(this.makeIssue(
          filePath, fn, 'long-function', 'low',
          `Function '${fn.name}' is ${functionLength} lines long (threshold: ${THRESHOLDS.functionLength.low})`,
          `Consider extracting some logic into helper functions.`,
        ));
      }

      // 3. Nesting Depth
      const depth = computeMaxNesting(fn.lines);
      if (depth > THRESHOLDS.nestingDepth.high) {
        issues.push(this.makeIssue(
          filePath, fn, 'deep-nesting', 'high',
          `Function '${fn.name}' has nesting depth of ${depth} (threshold: ${THRESHOLDS.nestingDepth.high})`,
          `Use early returns, guard clauses, or extract nested blocks into separate functions.`,
        ));
      } else if (depth > THRESHOLDS.nestingDepth.medium) {
        issues.push(this.makeIssue(
          filePath, fn, 'deep-nesting', 'medium',
          `Function '${fn.name}' has nesting depth of ${depth} (threshold: ${THRESHOLDS.nestingDepth.medium})`,
          `Consider using early returns or extracting deeply nested logic.`,
        ));
      }

      // 4. Parameter Count
      if (fn.paramCount > THRESHOLDS.paramCount.medium) {
        issues.push(this.makeIssue(
          filePath, fn, 'too-many-params', 'medium',
          `Function '${fn.name}' has ${fn.paramCount} parameters (threshold: ${THRESHOLDS.paramCount.medium})`,
          `Use an options object pattern: function ${fn.name}(options: Options) instead.`,
        ));
      } else if (fn.paramCount > THRESHOLDS.paramCount.low) {
        issues.push(this.makeIssue(
          filePath, fn, 'too-many-params', 'low',
          `Function '${fn.name}' has ${fn.paramCount} parameters (threshold: ${THRESHOLDS.paramCount.low})`,
          `Consider using an options object to group related parameters.`,
        ));
      }
    }

    return issues;
  }

  private makeIssue(
    filePath: string,
    fn: FunctionInfo,
    type: string,
    severity: Severity,
    message: string,
    suggestion: string,
  ): UnifiedIssue {
    return {
      id: '', // set in detect()
      detector: this.name,
      type,
      category: AIDefectCategory.OVER_ENGINEERING,
      severity,
      message,
      file: filePath,
      line: fn.startLine,
      endLine: fn.endLine,
      suggestion,
      fix: {
        description: suggestion,
        autoFixable: false,
      },
      confidence: 0.85,
      detectionSource: 'static',
    };
  }
}

export default OverEngineeringDetector;
