/**
 * English Message Catalog
 *
 * All user-visible strings in English.
 *
 * @since 0.4.0
 */

import type { Locale } from './types.js';

export const EN_MESSAGES: Record<string, string> = {
  // ─── Scan Messages ────────────────────────────────────────────

  'scan.start': 'Scanning {count} files...',
  'scan.complete': 'Scan complete in {duration}ms',
  'scan.noFiles': 'No files to scan',

  // ─── Detector Messages ────────────────────────────────────────

  'detector.hallucinated-import': 'Hallucinated import: package "{package}" does not exist in {registry}',
  'detector.hallucinated-import.offline': 'Cannot verify import "{package}" (offline mode)',
  'detector.hallucinated-import.phantom-function': 'Function "{name}" is called but not declared or imported in this file',
  'detector.stale-api': 'Deprecated API: "{api}" — use "{replacement}" instead',
  'detector.stale-api.since': 'Deprecated since {since}: "{api}" — use "{replacement}" instead',
  'detector.context-coherence.unused': 'Unused non-exported {kind} "{name}" (possible AI context loss)',
  'detector.context-coherence.duplicate': 'Duplicate {kind} name "{name}" in same scope',
  'detector.context-coherence.inconsistent-import': 'Inconsistent imports: "{module1}" and "{module2}" serve similar purpose',
  'detector.context-coherence.undefined-ref': 'Reference to undefined symbol "{name}"',
  'detector.over-engineering.params': 'Function "{name}" has {count} parameters (max recommended: {max})',
  'detector.over-engineering.nesting': 'Nesting depth {depth} exceeds maximum {max}',
  'detector.over-engineering.loc': 'Function "{name}" has {lines} lines (max recommended: {max})',
  'detector.over-engineering.complexity': 'Cyclomatic complexity {value} exceeds maximum {max}',
  'detector.security.hardcoded-secret': 'Possible hardcoded secret: {pattern}',
  'detector.security.eval': 'Dangerous eval/exec usage',
  'detector.security.weak-crypto': 'Weak cryptographic algorithm: {algo}',
  'detector.security.sql-injection': 'Possible SQL injection via string concatenation',
  'detector.incomplete.empty-catch': 'Empty catch block — potential error swallowing',
  'detector.incomplete.stub': 'Stub implementation found: {indicator}',

  // ─── Scoring ──────────────────────────────────────────────────

  'score.grade.excellent': 'Excellent',
  'score.grade.good': 'Good',
  'score.grade.fair': 'Fair',
  'score.grade.poor': 'Poor',
  'score.grade.fail': 'Fail',
  'score.dimension.faithfulness': 'AI Faithfulness',
  'score.dimension.freshness': 'Code Freshness',
  'score.dimension.coherence': 'Context Coherence',
  'score.dimension.quality': 'Implementation Quality',

  // ─── SLA ──────────────────────────────────────────────────────

  'sla.L1': 'L1 Fast — Structural analysis only',
  'sla.L2': 'L2 Standard — Structural + Embedding + Local AI',
  'sla.L3': 'L3 Deep — Structural + Embedding + Remote AI',

  // ─── Report ───────────────────────────────────────────────────

  'report.title': 'Open Code Review Report',
  'report.summary': '{total} issues found in {files} files',
  'report.noIssues': 'No issues found',
  'report.generated': 'Generated by Open Code Review v{version}',
  'report.project': 'Project: {name}',
  'report.date': 'Date: {date}',
  'report.score': 'Overall Score: {score}/100',
  'report.grade': 'Grade: {grade}',
  'report.filesScanned': 'Files Scanned: {count}',
  'report.passed': 'Passed: {count}',
  'report.failed': 'Failed: {count}',
  'report.threshold': 'Threshold: {threshold}',
  'report.status.passed': 'PASSED',
  'report.status.failed': 'FAILED',
  'report.duration': 'Duration: {duration}',
  'report.languages': 'Languages: {languages}',
  'report.dimensions': 'Scoring Dimensions',
  'report.issues': 'Issues',
  'report.issues.found': '{count} issues found',
  'report.more': '... and {count} more',

  // ─── CLI ──────────────────────────────────────────────────────

  'cli.scanning': 'Scanning...',
  'cli.done': 'Done!',
  'cli.error': 'Error: {message}',
  'cli.noFiles': 'No files matched the scan patterns',
  'cli.offline': 'Registry verification unavailable (offline). Package existence checks skipped.',

  // ─── Errors ───────────────────────────────────────────────────

  'error.parser.init': 'Failed to initialize parser: {message}',
  'error.registry.verify': 'Failed to verify package "{package}": {message}',
  'error.config.load': 'Failed to load configuration: {message}',
};

/**
 * Type for the message catalog.
 */
export type MessageCatalog = typeof EN_MESSAGES;

/**
 * Get the locale identifier for English.
 */
export const EN_LOCALE: Locale = 'en';
