name = "aicv-telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "b8d84addbb5cadd86f50fe23cb84f559"

# Secrets (set via wrangler secret put):
# TELEGRAM_BOT_TOKEN
# TELEGRAM_WEBHOOK_SECRET
