/**
 * SecurityPatternDetector Tests
 *
 * Tests detection of security anti-patterns commonly generated by AI:
 * hardcoded secrets, eval(), weak crypto, SQL injection, etc.
 *
 * @since 0.4.0 (V4)
 */

import { describe, it, expect } from 'vitest';
import { SecurityPatternDetector } from '../../src/detectors/v4/security-pattern.js';
import type { DetectorContext } from '../../src/detectors/v4/types.js';
import type { CodeUnit } from '../../src/ir/types.js';
import { createCodeUnit } from '../../src/ir/types.js';

// ─── Helpers ───────────────────────────────────────────────────────

function makeUnit(
  source: string,
  language: CodeUnit['language'] = 'typescript',
  file: string = 'test.ts',
): CodeUnit {
  return createCodeUnit({
    id: `func:${file}:fn`,
    file,
    language,
    kind: 'function',
    location: { startLine: 0, startColumn: 0, endLine: source.split('\n').length, endColumn: 0 },
    source,
  });
}

function createContext(): DetectorContext {
  return {
    projectRoot: '/project',
    allFiles: ['test.ts'],
  };
}

// ─── Tests ─────────────────────────────────────────────────────────

describe('SecurityPatternDetector', () => {
  const detector = new SecurityPatternDetector();

  it('should have correct metadata', () => {
    expect(detector.id).toBe('security-pattern');
    expect(detector.name).toBe('Security Pattern Detector');
    expect(detector.category).toBe('implementation');
    expect(detector.supportedLanguages).toEqual([]);
  });

  // ── Hardcoded Secrets ──────────────────────────────────────────

  it('should detect hardcoded API key pattern', async () => {
    // Use a clearly fake key (not matching any real provider format)
    const unit = makeUnit('const api_key = "test_fake_key_abcdef1234567890abcdef";');
    const results = await detector.detect([unit], createContext());
    const apiKeyResult = results.find(r => r.metadata?.patternId === 'hardcoded-api-key');
    expect(apiKeyResult).toBeDefined();
    expect(apiKeyResult!.severity).toBe('error');
    expect(apiKeyResult!.message).toContain('API key');
  });

  it('should detect hardcoded password', async () => {
    const unit = makeUnit('const password = "SuperSecret123!@#";');
    const results = await detector.detect([unit], createContext());
    const pwResult = results.find(r => r.metadata?.patternId === 'hardcoded-password');
    expect(pwResult).toBeDefined();
    expect(pwResult!.severity).toBe('error');
    expect(pwResult!.message).toContain('password');
  });

  it('should detect hardcoded auth token', async () => {
    const unit = makeUnit('const auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.abc123def456";');
    const results = await detector.detect([unit], createContext());
    const tokenResult = results.find(r => r.metadata?.patternId === 'hardcoded-token');
    expect(tokenResult).toBeDefined();
    expect(tokenResult!.severity).toBe('error');
  });

  it('should detect AWS access key pattern', async () => {
    const unit = makeUnit('const awsKey = "AKIAIOSFODNN7EXAMPLE";');
    const results = await detector.detect([unit], createContext());
    const awsResult = results.find(r => r.metadata?.patternId === 'aws-access-key');
    expect(awsResult).toBeDefined();
    expect(awsResult!.confidence).toBe(0.95);
  });

  it('should detect private key in source', async () => {
    const unit = makeUnit('const key = `-----BEGIN RSA PRIVATE KEY-----\nMIIE...`;');
    const results = await detector.detect([unit], createContext());
    const pkResult = results.find(r => r.metadata?.patternId === 'private-key');
    expect(pkResult).toBeDefined();
    expect(pkResult!.severity).toBe('error');
  });

  // ── Dangerous Functions ────────────────────────────────────────

  it('should detect eval() usage in TypeScript', async () => {
    const unit = makeUnit('const result = eval(userInput);');
    const results = await detector.detect([unit], createContext());
    const evalResult = results.find(r => r.metadata?.patternId === 'eval-usage-js');
    expect(evalResult).toBeDefined();
    expect(evalResult!.severity).toBe('error');
    expect(evalResult!.message).toContain('eval()');
    expect(evalResult!.message).toContain('code injection');
  });

  it('should detect eval() usage in Python', async () => {
    const unit = makeUnit('result = eval(user_input)', 'python', 'app.py');
    const results = await detector.detect([unit], createContext());
    const evalResult = results.find(r => r.metadata?.patternId === 'eval-usage-python');
    expect(evalResult).toBeDefined();
    expect(evalResult!.message).toContain('ast.literal_eval');
  });

  it('should detect exec() in Python', async () => {
    const unit = makeUnit('exec(dynamic_code)', 'python', 'app.py');
    const results = await detector.detect([unit], createContext());
    const execResult = results.find(r => r.metadata?.patternId === 'exec-usage-python');
    expect(execResult).toBeDefined();
  });

  // ── Weak Cryptography ──────────────────────────────────────────

  it('should detect MD5 usage', async () => {
    const unit = makeUnit('const hash = crypto.createHash("md5").update(data).digest("hex");');
    const results = await detector.detect([unit], createContext());
    const md5Result = results.find(r => r.metadata?.patternId === 'weak-hash-md5');
    expect(md5Result).toBeDefined();
    expect(md5Result!.severity).toBe('warning');
    expect(md5Result!.message).toContain('MD5');
  });

  it('should detect SHA-1 usage', async () => {
    const unit = makeUnit('const hash = crypto.createHash("sha1").update(data).digest("hex");');
    const results = await detector.detect([unit], createContext());
    const sha1Result = results.find(r => r.metadata?.patternId === 'weak-hash-sha1');
    expect(sha1Result).toBeDefined();
    expect(sha1Result!.message).toContain('SHA-1');
  });

  // ── SQL Injection ──────────────────────────────────────────────

  it('should detect SQL string concatenation', async () => {
    const unit = makeUnit('const query = "SELECT * FROM users WHERE id = " + req.params.id;');
    const results = await detector.detect([unit], createContext());
    const sqlResult = results.find(r => r.metadata?.patternId === 'sql-string-concat');
    expect(sqlResult).toBeDefined();
    expect(sqlResult!.severity).toBe('error');
    expect(sqlResult!.message).toContain('SQL');
    expect(sqlResult!.message).toContain('parameterized');
  });

  it('should detect SQL template literal injection', async () => {
    const unit = makeUnit('const query = `SELECT * FROM users WHERE id = ${req.params.id}`;');
    const results = await detector.detect([unit], createContext());
    const sqlResult = results.find(r => r.metadata?.patternId === 'sql-template-literal');
    expect(sqlResult).toBeDefined();
  });

  // ── Insecure Defaults ──────────────────────────────────────────

  it('should detect TLS verification disabled', async () => {
    const unit = makeUnit('const opts = { rejectUnauthorized: false };');
    const results = await detector.detect([unit], createContext());
    const tlsResult = results.find(r => r.metadata?.patternId === 'tls-verify-disabled');
    expect(tlsResult).toBeDefined();
    expect(tlsResult!.severity).toBe('error');
    expect(tlsResult!.message).toContain('TLS');
  });

  // ── No false positives ────────────────────────────────────────

  it('should not flag hash usage in non-security context (comments)', async () => {
    const unit = makeUnit(`
// This function uses MD5 for cache key generation
function generateCacheKey(data: string): string {
  return sha256(data);
}
    `.trim());
    const results = await detector.detect([unit], createContext());
    // The comment line should be skipped
    const md5InComments = results.filter(
      r => r.metadata?.patternId === 'weak-hash-md5' && (r.metadata?.matchedLine as string)?.startsWith('//'),
    );
    expect(md5InComments).toHaveLength(0);
  });

  it('should not flag eval in non-JS languages when pattern is language-specific', async () => {
    // The Python eval pattern should not fire on Go code
    const unit = makeUnit('result := eval(expr)', 'go', 'main.go');
    const results = await detector.detect([unit], createContext());
    const pythonEval = results.filter(r => r.metadata?.patternId === 'eval-usage-python');
    expect(pythonEval).toHaveLength(0);
  });

  // ── Language-specific patterns ─────────────────────────────────

  it('should detect Python f-string SQL injection', async () => {
    const unit = makeUnit(
      'query = f"SELECT * FROM users WHERE name = {request.args[\'name\']}"',
      'python',
      'app.py',
    );
    const results = await detector.detect([unit], createContext());
    const sqlResult = results.find(r => r.metadata?.patternId === 'sql-f-string-python');
    expect(sqlResult).toBeDefined();
    expect(sqlResult!.severity).toBe('error');
  });

  it('should detect Math.random() in JavaScript for security use', async () => {
    const unit = makeUnit('const token = Math.random().toString(36);');
    const results = await detector.detect([unit], createContext());
    const randomResult = results.find(r => r.metadata?.patternId === 'weak-random');
    expect(randomResult).toBeDefined();
    expect(randomResult!.message).toContain('crypto');
  });

  it('should skip empty source units', async () => {
    const unit = createCodeUnit({
      id: 'file:test.ts',
      file: 'test.ts',
      language: 'typescript',
      kind: 'file',
      location: { startLine: 0, startColumn: 0, endLine: 0, endColumn: 0 },
      source: '',
    });

    const results = await detector.detect([unit], createContext());
    expect(results).toHaveLength(0);
  });

  // ── Go-specific Security Patterns ──────────────────────────────

  it('should detect Go shell command injection via exec.Command("sh", "-c")', async () => {
    const unit = makeUnit(
      'cmd := exec.Command("sh", "-c", userInput)',
      'go',
      'main.go',
    );
    const results = await detector.detect([unit], createContext());
    const cmdResult = results.find(r => r.metadata?.patternId === 'go-command-injection');
    expect(cmdResult).toBeDefined();
    expect(cmdResult!.severity).toBe('error');
    expect(cmdResult!.message).toContain('command injection');
  });

  it('should detect Go SQL injection', async () => {
    const unit = makeUnit(
      'query := "SELECT * FROM users WHERE id = " + r.URL.Query().Get("id")',
      'go',
      'handler.go',
    );
    const results = await detector.detect([unit], createContext());
    const sqlResult = results.find(r => r.metadata?.patternId === 'go-sql-injection');
    expect(sqlResult).toBeDefined();
    expect(sqlResult!.severity).toBe('error');
  });

  it('should detect InsecureSkipVerify in Go', async () => {
    const unit = makeUnit(
      'tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}',
      'go',
      'client.go',
    );
    const results = await detector.detect([unit], createContext());
    const tlsResult = results.find(r => r.metadata?.patternId === 'tls-verify-disabled');
    expect(tlsResult).toBeDefined();
    expect(tlsResult!.severity).toBe('error');
  });

  // ── Java-specific Security Patterns ────────────────────────────

  it('should detect Java Runtime.exec() command injection', async () => {
    const unit = makeUnit(
      'Process p = Runtime.getRuntime().exec("cmd " + userInput);',
      'java',
      'App.java',
    );
    const results = await detector.detect([unit], createContext());
    const execResult = results.find(r => r.metadata?.patternId === 'java-command-injection');
    expect(execResult).toBeDefined();
    expect(execResult!.severity).toBe('error');
    expect(execResult!.message).toContain('ProcessBuilder');
  });

  it('should detect Java unsafe deserialization', async () => {
    const unit = makeUnit(
      'ObjectInputStream ois = new ObjectInputStream(new FileInputStream("data.ser"));',
      'java',
      'App.java',
    );
    const results = await detector.detect([unit], createContext());
    const deserResult = results.find(r => r.metadata?.patternId === 'java-unsafe-deserialization');
    expect(deserResult).toBeDefined();
    expect(deserResult!.severity).toBe('error');
    expect(deserResult!.message).toContain('remote code execution');
  });

  it('should detect Java setAccessible(true)', async () => {
    const unit = makeUnit(
      'field.setAccessible(true);',
      'java',
      'Reflect.java',
    );
    const results = await detector.detect([unit], createContext());
    const reflectResult = results.find(r => r.metadata?.patternId === 'java-reflective-access');
    expect(reflectResult).toBeDefined();
    expect(reflectResult!.severity).toBe('warning');
  });

  it('should detect Java MD5 usage via MessageDigest', async () => {
    const unit = makeUnit(
      'MessageDigest md = MessageDigest.getInstance("MD5");',
      'java',
      'HashUtil.java',
    );
    const results = await detector.detect([unit], createContext());
    const md5Result = results.find(r => r.metadata?.patternId === 'weak-hash-md5');
    expect(md5Result).toBeDefined();
  });

  // ── Kotlin-specific Security Patterns ──────────────────────────

  it('should detect Kotlin ProcessBuilder injection', async () => {
    const unit = makeUnit(
      'val process = ProcessBuilder("sh " + userInput)',
      'kotlin',
      'App.kt',
    );
    const results = await detector.detect([unit], createContext());
    const pbResult = results.find(r => r.metadata?.patternId === 'kotlin-process-builder-injection');
    expect(pbResult).toBeDefined();
    expect(pbResult!.severity).toBe('error');
  });

  it('should detect Kotlin unsafe deserialization (inherits Java)', async () => {
    const unit = makeUnit(
      'val ois = ObjectInputStream(ByteArrayInputStream(data))',
      'kotlin',
      'Deserialize.kt',
    );
    const results = await detector.detect([unit], createContext());
    const deserResult = results.find(r => r.metadata?.patternId === 'java-unsafe-deserialization');
    expect(deserResult).toBeDefined();
  });

  it('should detect Kotlin hardcoded password', async () => {
    const unit = makeUnit(
      'val password = "SuperSecretKotlinPassword123"',
      'kotlin',
      'Config.kt',
    );
    const results = await detector.detect([unit], createContext());
    const pwResult = results.find(r => r.metadata?.patternId === 'hardcoded-password');
    expect(pwResult).toBeDefined();
    expect(pwResult!.severity).toBe('error');
  });
});
