/**
 * Go Package Database — Standard library + Top 100 common third-party packages.
 *
 * Used for hallucinated import detection in offline mode
 * (when Go module proxy is not available).
 *
 * @since 0.5.0
 */

export const GO_STANDARD_LIBRARY = new Set([
  'fmt', 'os', 'io', 'bufio', 'bytes', 'strings', 'strconv',
  'unicode', 'unicode/utf8', 'unicode/utf16', 'regexp', 'sort', 'slices',
  'math', 'math/big', 'math/cmplx', 'math/rand', 'time',
  'errors', 'log', 'log/syslog', 'flag',
  'context', 'sync', 'sync/atomic', 'sync/atomic',
  'reflect', 'unsafe', 'runtime', 'runtime/debug', 'runtime/pprof', 'runtime/trace',
  'testing', 'testing/fstest', 'testing/iotest', 'testing/slogtest', 'testing/quick',
  'net', 'net/http', 'net/http/cgi', 'net/http/cookiejar', 'net/http/fcgi',
  'net/http/httptest', 'net/http/httptrace', 'net/http/httputil', 'net/http/pprof',
  'net/mail', 'net/rpc', 'net/rpc/jsonrpc', 'net/smtp', 'net/textproto', 'net/url',
  'net/dns', 'net/netip',
  'encoding', 'encoding/ascii85', 'encoding/base32', 'encoding/base64',
  'encoding/binary', 'encoding/csv', 'encoding/gob', 'encoding/hex',
  'encoding/json', 'encoding/pem', 'encoding/xml',
  'crypto', 'crypto/aes', 'crypto/cipher', 'crypto/des', 'crypto/dsa',
  'crypto/ecdsa', 'crypto/ed25519', 'crypto/elliptic', 'crypto/hmac',
  'crypto/md5', 'crypto/rand', 'crypto/rc4', 'crypto/rsa', 'crypto/sha1',
  'crypto/sha256', 'crypto/sha512', 'crypto/subtle', 'crypto/tls', 'crypto/x509',
  'compress', 'compress/bzip2', 'compress/flate', 'compress/gzip', 'compress/lzw', 'compress/zlib',
  'archive', 'archive/tar', 'archive/zip',
  'database', 'database/sql', 'database/sql/driver',
  'html', 'html/template', 'text', 'text/tabwriter', 'text/template', 'text/template/parse',
  'text/scanner', 'text/search', 'path', 'path/filepath',
  'debug', 'debug/buildinfo', 'debug/dwarf', 'debug/elf', 'debug/gosym',
  'debug/macho', 'debug/pe', 'debug/plan9obj',
  'go', 'go/ast', 'go/build', 'go/constant', 'go/doc', 'go/format', 'go/importer',
  'go/parser', 'go/printer', 'go/token', 'go/types', 'go/scanner',
  'embed', 'plugin', 'syscall', 'signal',
  'image', 'image/color', 'image/draw', 'image/gif', 'image/jpeg', 'image/png',
  'image/color/palette',
  'mime', 'mime/multipart', 'mime/quotedprintable',
  'expvar', 'index/suffixarray', 'container/heap', 'container/list', 'container/ring',
  'os/exec', 'os/signal', 'os/user', 'os/info',
  'io/fs', 'io/ioutil',
  'hash', 'hash/adler32', 'hash/crc32', 'hash/crc64', 'hash/fnv', 'hash/maphash',
]);

/**
 * Top 100 most popular Go third-party packages (github.com/* and others).
 */
export const GO_THIRD_PARTY = new Set([
  'github.com/gin-gonic/gin',
  'github.com/gorilla/mux',
  'github.com/gorilla/handlers',
  'github.com/gorilla/websocket',
  'github.com/go-chi/chi',
  'github.com/labstack/echo',
  'github.com/fiber/fiber',
  'github.com/gofiber/fiber',
  'github.com/golang/protobuf',
  'github.com/grpc/grpc-go',
  'google.golang.org/grpc',
  'google.golang.org/protobuf',
  'github.com/go-sql-driver/mysql',
  'github.com/lib/pq',
  'github.com/jackc/pgx',
  'github.com/mattn/go-sqlite3',
  'github.com/redis/go-redis',
  'go.mongodb.org/mongo-driver',
  'github.com/olivere/elastic',
  'github.com/go-redis/redis',
  'github.com/gomodule/redigo',
  'github.com/rabbitmq/amqp091-go',
  'github.com/streadway/amqp',
  'github.com/confluentinc/confluent-kafka-go',
  'github.com/segmentio/kafka-go',
  'github.com/IBM/sarama',
  'github.com/urfave/cli',
  'github.com/spf13/cobra',
  'github.com/spf13/viper',
  'github.com/jessevdk/go-flags',
  'github.com/mitchellh/mapstructure',
  'github.com/sirupsen/logrus',
  'go.uber.org/zap',
  'github.com/rs/zerolog',
  'github.com/go-kit/log',
  'logur.dev/logur',
  'go.uber.org/fx',
  'github.com/google/wire',
  'github.com/facebookgo/inject',
  'github.com/stretchr/testify',
  'github.com/onsi/ginkgo',
  'github.com/onsi/gomega',
  'github.com/pmezard/go-difflib',
  'github.com/davecgh/go-spew',
  'github.com/google/uuid',
  'github.com/pborman/uuid',
  'github.com/gofrs/uuid',
  'github.com/oklog/ulid',
  'github.com/sony/sonyflake',
  'github.com/bwmarrin/snowflake',
  'github.com/pkg/errors',
  'github.com/go-errors/errors',
  'github.com/hashicorp/errwrap',
  'github.com/hashicorp/go-multierror',
  'github.com/getsentry/sentry-go',
  'go.opentelemetry.io/otel',
  'go.opentelemetry.io/otel/sdk',
  'go.opentelemetry.io/otel/exporters/jaeger',
  'go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp',
  'github.com/prometheus/client_golang',
  'github.com/prometheus/client_model',
  'github.com/prometheus/common',
  'github.com/gorilla/schema',
  'github.com/google/go-github',
  'github.com/dgrijalva/jwt-go',
  'github.com/golang-jwt/jwt',
  'github.com/golang-jwt/jwt/v4',
  'github.com/golang-jwt/jwt/v5',
  'github.com/casbin/casbin',
  'github.com/go-playground/validator',
  'github.com/go-playground/locales',
  'github.com/golang/groupcache',
  'github.com/hashicorp/golang-lru',
  'github.com/patrickmn/go-cache',
  'github.com/allegro/bigcache',
  'github.com/coocood/freecache',
  'github.com/dgraph-io/ristretto',
  'github.com/jinzhu/gorm',
  'gorm.io/gorm',
  'gorm.io/driver/mysql',
  'gorm.io/driver/postgres',
  'gorm.io/driver/sqlite',
  'github.com/ent/ent',
  'entgo.io/ent',
  'github.com/xeipuuv/gojsonschema',
  'github.com/tidwall/gjson',
  'github.com/tidwall/sjson',
  'github.com/spf13/cast',
  'github.com/google/jsonapi',
  'github.com/gin-contrib/cors',
  'github.com/rs/cors',
  'github.com/labstack/echo/v4',
  'github.com/go-chi/cors',
  'github.com/unrolled/secure',
  'github.com/go-chi/render',
  'gopkg.in/yaml.v2',
  'gopkg.in/yaml.v3',
  'gopkg.in/vmihailenco/msgpack.v2',
  'gopkg.in/ini.v1',
  'github.com/BurntSushi/toml',
  'github.com/spf13/afero',
  'github.com/stretchr/objx',
  'cloud.google.com/go',
  'github.com/aws/aws-sdk-go',
  'github.com/aws/aws-sdk-go-v2',
  'github.com/azure/azure-sdk-for-go',
  'github.com/hashicorp/consul/api',
  'github.com/hashicorp/vault/api',
  'github.com/segmentio/encoding',
  'golang.org/x/crypto',
  'golang.org/x/net',
  'golang.org/x/text',
  'golang.org/x/time',
  'golang.org/x/sys',
  'golang.org/x/exp',
  'golang.org/x/tools',
  'golang.org/x/mod',
  'github.com/mitchellh/cli',
  'github.com/fatih/color',
  'github.com/jmoiron/sqlx',
  'github.com/uptrace/bun',
  'github.com/uptrace/bun/dbfixture',
  'github.com/volatiletech/null/v8',
  'github.com/samber/lo',
  'github.com/antihax/optional',
]);

/** Combined Go package set (stdlib + top third-party). */
export const GO_ALL_KNOWN_PACKAGES = new Set([
  ...GO_STANDARD_LIBRARY,
  ...GO_THIRD_PARTY,
]);
